### ISSUE TITLE
AttributeError: 'str' object has no attribute 'write'

### ISSUE THREAD

**Issue by pawel-biernacki-roche** [miki725/xunitmerge#16]
Hi!

After upgrade to v1.0.4 we get the following issue in our CI which uses `xunitmerge`:

```
$ find ./ -type f -name "test-report-*.xml"  -print0 | xargs -0 -I {} poetry run xunitmerge {} test-report.xml
Traceback (most recent call last):
  File "/root/miniforge/lib/python3.12/xml/etree/ElementTree.py", line 743, in _get_writer
    write = file_or_filename.write
            ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'write'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/project-HyJrY7Fe-py3.12/bin/xunitmerge", line 26, in <module>
    merge_xunit(args.report, args.output)
  File "/root/.cache/pypoetry/virtualenvs/project-HyJrY7Fe-py3.12/lib/python3.12/site-packages/xunitmerge/xmerge.py", line 130, in merge_xunit
    merged.write(output, encoding='utf-8', xml_declaration=True)
  File "/root/miniforge/lib/python3.12/xml/etree/ElementTree.py", line 729, in write
    serialize(write, self._root, qnames, namespaces,
  File "/root/.cache/pypoetry/virtualenvs/project-HyJrY7Fe-py3.12/lib/python3.12/site-packages/xunitmerge/xmerge.py", line 70, in _serialize_xml
    original_serialize(write, elem, *args, **kwargs)
  File "/root/miniforge/lib/python3.12/xml/etree/ElementTree.py", line 892, in _serialize_xml
    _serialize_xml(write, e, qnames, None,
  File "/root/.cache/pypoetry/virtualenvs/project-HyJrY7Fe-py3.12/lib/python3.12/site-packages/xunitmerge/xmerge.py", line 70, in _serialize_xml
    original_serialize(write, elem, *args, **kwargs)
  File "/root/miniforge/lib/python3.12/xml/etree/ElementTree.py", line 892, in _serialize_xml
    _serialize_xml(write, e, qnames, None,
  File "/root/.cache/pypoetry/virtualenvs/project-HyJrY7Fe-py3.12/lib/python3.12/site-packages/xunitmerge/xmerge.py", line 70, in _serialize_xml
    original_serialize(write, elem, *args, **kwargs)
  File "/root/miniforge/lib/python3.12/xml/etree/ElementTree.py", line 892, in _serialize_xml
    _serialize_xml(write, e, qnames, None,
  File "/root/.cache/pypoetry/virtualenvs/project-HyJrY7Fe-py3.12/lib/python3.12/site-packages/xunitmerge/xmerge.py", line 64, in _serialize_xml
    write(TAG_PATTERN.format(
TypeError: write() argument must be str, not bytes
Traceback (most recent call last):
  File "/root/miniforge/lib/python3.12/xml/etree/ElementTree.py", line 743, in _get_writer
    write = file_or_filename.write
            ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'write'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/project-HyJrY7Fe-py3.12/bin/xunitmerge", line 26, in <module>
    merge_xunit(args.report, args.output)
  File "/root/.cache/pypoetry/virtualenvs/project-HyJrY7Fe-py3.12/lib/python3.12/site-packages/xunitmerge/xmerge.py", line 130, in merge_xunit
    merged.write(output, encoding='utf-8', xml_declaration=True)
  File "/root/miniforge/lib/python3.12/xml/etree/ElementTree.py", line 729, in write
    serialize(write, self._root, qnames, namespaces,
  File "/root/.cache/pypoetry/virtualenvs/project-HyJrY7Fe-py3.12/lib/python3.12/site-packages/xunitmerge/xmerge.py", line 70, in _serialize_xml
    original_serialize(write, elem, *args, **kwargs)
  File "/root/miniforge/lib/python3.12/xml/etree/ElementTree.py", line 892, in _serialize_xml
    _serialize_xml(write, e, qnames, None,
  File "/root/.cache/pypoetry/virtualenvs/project-HyJrY7Fe-py3.12/lib/python3.12/site-packages/xunitmerge/xmerge.py", line 70, in _serialize_xml
    original_serialize(write, elem, *args, **kwargs)
  File "/root/miniforge/lib/python3.12/xml/etree/ElementTree.py", line 892, in _serialize_xml
    _serialize_xml(write, e, qnames, None,
  File "/root/.cache/pypoetry/virtualenvs/project-HyJrY7Fe-py3.12/lib/python3.12/site-packages/xunitmerge/xmerge.py", line 70, in _serialize_xml
    original_serialize(write, elem, *args, **kwargs)
  File "/root/miniforge/lib/python3.12/xml/etree/ElementTree.py", line 892, in _serialize_xml
    _serialize_xml(write, e, qnames, None,
  File "/root/.cache/pypoetry/virtualenvs/project-HyJrY7Fe-py3.12/lib/python3.12/site-packages/xunitmerge/xmerge.py", line 64, in _serialize_xml
    write(TAG_PATTERN.format(
TypeError: write() argument must be str, not bytes
Traceback (most recent call last):
  File "/root/miniforge/lib/python3.12/xml/etree/ElementTree.py", line 743, in _get_writer
    write = file_or_filename.write
            ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'write'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/project-HyJrY7Fe-py3.12/bin/xunitmerge", line 26, in <module>
    merge_xunit(args.report, args.output)
  File "/root/.cache/pypoetry/virtualenvs/project-HyJrY7Fe-py3.12/lib/python3.12/site-packages/xunitmerge/xmerge.py", line 130, in merge_xunit
    merged.write(output, encoding='utf-8', xml_declaration=True)
  File "/root/miniforge/lib/python3.12/xml/etree/ElementTree.py", line [729](https://code.roche.com/project/project/-/jobs/66646229#L729), in write
    serialize(write, self._root, qnames, namespaces,
  File "/root/.cache/pypoetry/virtualenvs/project-HyJrY7Fe-py3.12/lib/python3.12/site-packages/xunitmerge/xmerge.py", line 70, in _serialize_xml
    original_serialize(write, elem, *args, **kwargs)
  File "/root/miniforge/lib/python3.12/xml/etree/ElementTree.py", line 892, in _serialize_xml
    _serialize_xml(write, e, qnames, None,
  File "/root/.cache/pypoetry/virtualenvs/project-HyJrY7Fe-py3.12/lib/python3.12/site-packages/xunitmerge/xmerge.py", line 70, in _serialize_xml
    original_serialize(write, elem, *args, **kwargs)
  File "/root/miniforge/lib/python3.12/xml/etree/ElementTree.py", line 892, in _serialize_xml
    _serialize_xml(write, e, qnames, None,
  File "/root/.cache/pypoetry/virtualenvs/project-HyJrY7Fe-py3.12/lib/python3.12/site-packages/xunitmerge/xmerge.py", line 70, in _serialize_xml
    original_serialize(write, elem, *args, **kwargs)
  File "/root/miniforge/lib/python3.12/xml/etree/ElementTree.py", line 892, in _serialize_xml
    _serialize_xml(write, e, qnames, None,
  File "/root/.cache/pypoetry/virtualenvs/project-HyJrY7Fe-py3.12/lib/python3.12/site-packages/xunitmerge/xmerge.py", line 64, in _serialize_xml
    write(TAG_PATTERN.format(
TypeError: write() argument must be str, not bytes
```

Any idea what what could be going wrong and if there is a way to fix it? Thanks!
